from app.models.usuario import Usuario
from app.models.responsavel import Responsavel
from app.models.aluno import Aluno
from app.models.autorizado import Autorizado
from app.models.movimentacao import Movimentacao
from app.models.auditoria_log import AuditoriaLog
from app.models.aceite_termo import AceiteTermo
from app.models.token_recuperacao import TokenRecuperacao
from app.models.email_brevo import EmailBrevo
from app.models.codigo_2fa import Codigo2FA
from app.models.autorizacao import Autorizacao